# Generated by Django 5.1.3 on 2024-12-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='start_date',
        ),
        migrations.AddField(
            model_name='batch',
            name='end_year',
            field=models.IntegerField(default='timezone.now'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='start_year',
            field=models.IntegerField(default='now'),
            preserve_default=False,
        ),
    ]
