# Generated by Django 4.2.7 on 2024-11-21 14:43

import Companies.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True, help_text='Short description about the company', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Drive title (e.g., Software Engineer Hiring)', max_length=255)),
                ('drive_date', models.DateField(help_text='Date of the placement Drive')),
                ('applications_starts', models.DateField(auto_now_add=True)),
                ('applications_ends', models.DateField(auto_now_add=True)),
                ('job_description', models.FileField(blank=True, help_text='Upload Job Description ', null=True, upload_to=Companies.models.jd_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompanyDrive', to='Companies.companies')),
            ],
        ),
    ]
